const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={token:localStorage.getItem('wayss_token'),user:null,messages:[],history:JSON.parse(localStorage.getItem('wayss_history')||'[]'),mode:'chat',file:null,authMode:'login'};
const api=async(path,opts={})=>{const headers={...(opts.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch('/api'+path,{...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function setView(view){['home','chat','login'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==view));$('#composerWrap').classList.toggle('hidden',view!=='chat')}
function renderHistory(){const h=$('#history');h.innerHTML='';state.history.slice().reverse().forEach((x,i)=>{const b=document.createElement('button');b.textContent=x.title||'Untitled chat';b.onclick=()=>loadHistory(state.history.length-1-i);h.appendChild(b)})}
function saveHistory(){localStorage.setItem('wayss_history',JSON.stringify(state.history.slice(-50)));renderHistory()}
function loadHistory(i){const x=state.history[i];if(!x)return;state.messages=x.messages||[];$('#chatTitle').textContent=x.title||'Chat';setView('chat');renderMessages()}
function renderMessages(){const box=$('#messages');box.innerHTML='';state.messages.forEach(m=>{const row=document.createElement('div');row.className='msg '+m.role;const av=document.createElement('img');av.className='avatar';av.src='/assets/wayss-icon.svg';const bubble=document.createElement('div');bubble.className='bubble';if(m.image){const im=document.createElement('img');im.className='generated';im.src=m.image;bubble.appendChild(im)}else{bubble.innerHTML=formatText(m.content||'')}row.append(av,bubble);box.appendChild(row)});window.scrollTo(0,document.body.scrollHeight)}
function formatText(s){const esc=s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');return esc.replace(/\`\`\`([\s\S]*?)\`\`\`/g,'<pre class="codeblock">$1</pre>').replace(/\n/g,'<br>')}
function add(role,content='',extra={}){state.messages.push({role,content,...extra});renderMessages()}
async function send(){const text=$('#prompt').value.trim();if(!text&&state.mode==='chat'&&!state.file)return;if(!state.token){setView('login');toast('Sign in to use Wayss');return}$('#prompt').value='';
if(state.mode==='image'){add('user',text);add('assistant','Generating your image…');try{const d=await api('/image/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:text})});state.messages.pop();add('assistant','',{image:d.image});saveCurrent(text)}catch(e){state.messages.pop();add('assistant',e.message)}}
else if(state.mode==='edit'){add('user',text);add('assistant','Editing your image…');try{const fd=new FormData();fd.append('image',state.file);fd.append('prompt',text);const d=await api('/image/edit',{method:'POST',body:fd});state.messages.pop();add('assistant','',{image:d.image});clearFile()}catch(e){state.messages.pop();add('assistant',e.message)}}
else if(state.mode==='search'){add('user',text);add('assistant','Searching the web…');try{const d=await api('/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:text})});state.messages.pop();let c=d.answer||'';if(d.results?.length)c+=(c?'\n\n':'')+d.results.map(r=>`${r.title}\n${r.url}\n${r.content}`).join('\n\n');add('assistant',c);saveCurrent(text)}catch(e){state.messages.pop();add('assistant',e.message)}}
else if(state.mode==='vision'){add('user',text||'Analyze this image.');add('assistant','Analyzing your image…');try{const fd=new FormData();fd.append('image',state.file);fd.append('prompt',text||'Analyze this image in detail.');const d=await api('/vision',{method:'POST',body:fd});state.messages.pop();add('assistant',d.message);clearFile();saveCurrent(text||'Image analysis')}catch(e){state.messages.pop();add('assistant',e.message)}}
else{if(state.file){const fd=new FormData();fd.append('file',state.file);add('user',text||`Analyze ${state.file.name}`);add('assistant','Reading your file…');try{const d=await api('/files/read',{method:'POST',body:fd});state.messages.pop();const context=d.text?`File: ${d.name}\n\n${d.text}`:`File received: ${d.name}. ${d.note||''}`;state.messages.pop();state.messages.push({role:'user',content:text||`Analyze ${d.name}`});const msgs=state.messages.slice(-20).concat([{role:'user',content:`Use this uploaded file as context:\n${context}\n\nTask: ${text||'Analyze and summarize it.'}`}]);const a=await api('/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:msgs})});clearFile();add('assistant',a.message);saveCurrent(text||d.name)}catch(e){state.messages.pop();add('assistant',e.message)}}else{add('user',text);add('assistant','Thinking…');try{const d=await api('/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:state.messages.slice(0,-1).concat([{role:'user',content:text}]),system:'You are Wayss, a helpful, direct, capable AI assistant. Answer naturally, be accurate, and use Markdown/code when useful.'})});state.messages.pop();add('assistant',d.message);saveCurrent(text)}catch(e){state.messages.pop();add('assistant',e.message)}}}
state.mode='chat';$('#chatTitle').textContent='Chat'}
function saveCurrent(title){state.history.push({title:(title||'New chat').slice(0,70),messages:state.messages});saveHistory()}
function chooseMode(mode){state.mode=mode;setView('chat');$('#chatTitle').textContent={image:'Image generation',edit:'Image editing',vision:'Image analysis',search:'Web search',code:'Code assistant',voice:'Voice chat'}[mode]||'Chat';$('#prompt').placeholder={image:'Describe the image you want…',edit:'Describe how to transform this image…',vision:'What should Wayss analyze in this image?',search:'What should Wayss search for?',code:'What should Wayss code?',voice:'Speak or type…'}[mode]||'Message Wayss…';if(mode==='voice')startVoice()}
function clearFile(){state.file=null;$('#fileInput').value='';$('#attachmentPreview').innerHTML=''}
function handleFile(file){if(!file)return;state.file=file;const p=$('#attachmentPreview');p.innerHTML='';const wrap=document.createElement('div');wrap.className='attachment';if(file.type.startsWith('image/')){const im=document.createElement('img');im.src=URL.createObjectURL(file);wrap.appendChild(im)}const span=document.createElement('span');span.textContent=file.name;const x=document.createElement('button');x.textContent='×';x.onclick=clearFile;wrap.append(span,x);p.appendChild(wrap);state.mode=file.type.startsWith('image/')?'vision':'chat'}
function startVoice(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){toast('Voice input is not supported in this browser.');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();r.lang='en-IN';r.interimResults=false;r.onresult=e=>{$('#prompt').value=e.results[0][0].transcript;send()};r.onerror=()=>toast('Voice input stopped.');r.start();toast('Listening…')}
async function init(){renderHistory();$('#themeBtn').onclick=()=>document.body.classList.toggle('light');$('#newChat').onclick=()=>{state.messages=[];setView('home');$('#chatTitle').textContent='New chat'};$('#clearChats').onclick=()=>{state.history=[];saveHistory()};$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#settingsBtn').onclick=()=>toast('Settings are ready for future account preferences.');$('#sendBtn').onclick=send;$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#attachBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>handleFile(e.target.files[0]);$('#voiceBtn').onclick=startVoice;$$('[data-tool]').forEach(b=>b.onclick=()=>{const m=b.dataset.tool;if(m==='file')$('#fileInput').click();else chooseMode(m)});$$('[data-action]').forEach(b=>b.onclick=()=>{const m=b.dataset.action;if(m==='file')$('#fileInput').click();else chooseMode(m)});$('#searchNav').onclick=()=>chooseMode('search');$('#libraryNav').onclick=()=>toast('Your generated content and uploaded files stay inside chats.');$('#logoutBtn').onclick=()=>{state.token=null;state.user=null;localStorage.removeItem('wayss_token');showUser();setView('login')};$('#toggleAuth').onclick=()=>{state.authMode=state.authMode==='login'?'signup':'login';$('#authSubmit').textContent=state.authMode==='login'?'Sign in':'Create account';$('#toggleAuth').textContent=state.authMode==='login'?'Create account':'Already have an account? Sign in';$('#authName').classList.toggle('hidden',state.authMode==='login')};$('#authSubmit').onclick=authSubmit;
if(state.token){try{const d=await api('/me');state.user=d.user;showUser();setView('home')}catch{state.token=null;localStorage.removeItem('wayss_token');showUser();setView('login')}}else{showUser();setView('login');$('#authName').classList.add('hidden')}}
async function authSubmit(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();$('#authError').textContent='';try{const d=await api(state.authMode==='login'?'/auth/login':'/auth/signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,email,password})});state.token=d.token;localStorage.setItem('wayss_token',d.token);state.user=d.user;showUser();setView('home')}catch(e){$('#authError').textContent=e.message}}
function showUser(){const u=state.user;$('#sideName').textContent=u?.name||'Guest';$('#sideEmail').textContent=u?.email||'Not signed in';$('#helloName').textContent=u?.name||'there';$('#logoutBtn').classList.toggle('hidden',!u)}
init();